### ISSUE TITLE
App crash during display driver update

### ISSUE THREAD

**Issue by mehistaken** [nvdweem/PCPanel#17] opened 2022-11-11 15:44 UTC
**Describe the bug:**
App crashed (I believe) during nVidia driver update

**Steps to reproduce:**
update display driver using geforece experience 

**Expected behavior:**
Not crash

**Additional context:**

```
Faulting application name: PCPanel.exe, version: 22.45.62047.0, time stamp: 0xe052982d
Faulting module name: SndCtrl.1.6-SNAPSHOT.dll, version: 0.0.0.0, time stamp: 0x636032ed
Exception code: 0xc0000005
Fault offset: 0x0000000000001531
Faulting process id: 0x0x4650
Faulting application start time: 0x0x1D8F50FD58E055B
Faulting application path: C:\Users\mehis\AppData\Local\PCPanel\PCPanel.exe
Faulting module path: C:\Users\mehis\AppData\Local\Temp\SndCtrl.1.6-SNAPSHOT.dll
Report Id: 26bec9a8-2b07-4103-a500-737827f845ad
Faulting package full name: 
Faulting package-relative application ID: 
```

Crash dump: https://www.dropbox.com/s/kbkwii1lk3zjm46/PCPanel.exe.18000.zip?dl=0

**Comment by nvdweem** [comment] 2022-11-12 19:05
The crash dump indicates that this is a duplicate of the issue that is mentioned in #13 (a bit later on in the thread).
I'm aware that installing display drivers isn't something you probably do very often, but you can try the latest snapshot and see if that works. The 22.45.62047.0 version is a bit older already (and I still need to make the snapshot versions more clear to be able to differentiate between them).

**Comment by nvdweem** [comment] 2022-11-26 15:08
Closing the issue since there wasn't any response for a while and the bug should be fixed. Please create a new issue if the app crashes again.

**Closed by nvdweem** 2022-11-26 15:08 UTC
Labels: bug
