### ISSUE TITLE
Toggle Device options

### ISSUE THREAD

**Issue by DrowningWhale** [nvdweem/PCPanel#13] opened 2022-10-29 04:00 UTC
It would be nice to have options for the toggle device option for knob buttons similar to what is available for Sound Device advanced. Currently if you put a speaker into the selected devices, it only sets default system device. It would be nice to have the option to select what default to change. For example, I have the SS Arctis 7 which splits game and chat audio. I would like the option to change only the "Communication Default Device" between 2 speakers instead of system default.

**Comment by nvdweem** [comment] 2022-10-29 10:42
I added a 'Toggle Device Advanced' which is essentially the 'Sound Device Advanced' but allows adding more than 1 so that you can toggle. It might be a bit more verbose than just adding an option in the regular 'Toggle Device' but this way it is possible to switch both the input and output at the same time for swtiching between speakers/mic or headset/mic.
![image](https://user-images.githubusercontent.com/830783/198826901-63c951d3-e32e-4af2-8671-e99c167120dd.png)

**Comment by DrowningWhale** [comment] 2022-11-01 00:57
Tried the 1.6 Pre-Release and it works great. The only thing I would change is adding a blank option in the dropdown for both advanced options. Alternative would be to delete and re-add. Thanks!

**Comment by nvdweem** [comment] 2022-11-01 06:11
The 'Select or give a name of' label is there to indicate that it is possible to type a device name, that way it is possible to clear the option. There are two reasons why it is possible to type a name:
- Because this works on name and not id, it still shows the device name when the actual device is not connected
- It works on partial matches. For me the `Microphone (Yeti Classic)` will reconnect every now and then as `Microphone (Yeti Classic) (1)`, using the name that means that it will still work.

I'll add the empty option anyway so that it becomes easier to clear an option using just the mouse :).

**Comment by DrowningWhale** [comment] 2022-11-02 03:28
Didn't even know I can type there. I'm also getting a "Child process exited with code 3221225477" on initial startup and waking from sleep. Not sure if it's related to this update.

**Comment by nvdweem** [comment] 2022-11-02 06:15
It might be related, #11 is about the random crashes.
Are you running the most recent 1.6-SNAPSHOT (I really should start numbering those)? Right clicking the PCPanel.exe should show a file version in the Details tab, the latest snapshot is 22.45.62074.0
If you are not using that version it's best to download the latest snapshot, if you are using it, it could help me find the issue if there are recent `PCPanel.exe.[nr].dmp` files in `%localappdata%\CrashDumps` that you could upload?

**Comment by mehistaken** [comment] 2022-11-02 06:22
I've been running that snapshot since yesterday and no crashes yet!

I have a probably unrelated issue with the app. It won't run on windows start up no matter what I do.
It's enabled in Apps > Startup
Tried adding to `shell:common startup` and `shell:startup`
Tried regedit `HKLM/SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

Just haven't got to group policy yet cause I'm on Win11 Home and it's a hassle to install it

```
Edition		Windows 11 Home
Version		22H2
Installed on	‎2022-‎10-‎05
OS build	22621.674
Experience	Windows Feature Experience Pack 1000.22634.1000.0
```

**Comment by DrowningWhale** [comment] 2022-11-02 16:20
Not on that version, will update and be on the watch

**Comment by nvdweem** [comment] 2022-11-05 11:41
> I have a probably unrelated issue with the app. It won't run on windows start up no matter what I do.

The installer should put the software in the `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` and afaik that should be sufficient.
I do notice that for me the original software is also still in there but doesn't start either, but that is because I disabled it in the 'Task Manager' > 'Startup apps' pane. Perhaps that's the case for you with this version?

**Comment by mehistaken** [comment] 2022-11-05 14:47
It's in there with the `quiet` flag, but doesn't seem to load
I'm going to try it without the flag

**Comment by DrowningWhale** [comment] 2022-11-08 07:03
On latest version I can get to 22.45.062047. Posting dumps.
[PCPanel.Dumps.zip](https://github.com/nvdweem/PCPanel/files/9958542/PCPanel.Dumps.zip)

**Comment by nvdweem** [comment] 2022-11-08 20:01
I made some changes to try and prevent the crashes from the dumps. It seems that there is a device that doesn't have an IAudioSessionControl interface (so it can't be volume controlled) which wasn't expected.
I haven't added any additional logging to find what device is the cause, but the specific crash shouldn't occur anymore with the latest snapshot.

**Comment by mehistaken** [comment] 2022-11-09 13:57
> It's in there with the `quiet` flag, but doesn't seem to load I'm going to try it without the flag

So I did 2 things and now it works on startup
- took the app _off_ "run as administrator" 
- checked "register this program for restart"

I'm going to double check which one (or both?) did the trick

**Comment by nvdweem** [comment] 2022-11-13 16:31
Closing the issue because the original enhancement is implemented. If the other issues are still present then a new ticket for those can be created.

**Closed by nvdweem** 2022-11-13 16:31 UTC
Labels: enhancement
