### ISSUE TITLE
EPOS Conflict with PCPanel 

### ISSUE THREAD

**Issue by iamnotracist** [nvdweem/PCPanel#14] opened 2022-11-03 00:17 UTC
**Describe the bug:**

PCPanel Software will not start when EPOS software is installed
Error:
Child process exited with code 1

**Steps to reproduce:**

Install EPOS software 

**Expected behavior:**

EPOS should coexist peacefully with PCPanel

**Additional context:**

Windows 11
EPOS Software Version 1.11.0.1102
PCPanel 1.6 Snapshot

**Comment by iamnotracist** [comment] 2022-11-03 00:26
PCPanel Software will start when using version 1.1

**Comment by nvdweem** [comment] 2022-11-03 06:21
Windows should write a `PCPanel.exe.[nr].dmp` file in `%localappdata%\CrashDumps`. Are there files? If so, could you upload the most recent one? It might help me identify the issue without having to install the software I don't need :).

If I have time I'll also try to install the software locally so see if it crashes for me as well.

**Comment by nvdweem** [comment] 2022-11-05 09:26
I installed a VM and the 'EPOS Gaming Suite' (not sure what other 'EPOS software' you would mean) but the PCPanel software still starts just fine.
So, I either installed the wrong software, I actually need an EPOS device or the issue is an interaction with something else.

This means that I won't really be able to investigate without having a crashdump.

**Comment by iamnotracist** [comment] 2022-11-08 23:54
Yes, that is the software package I was talking about. After your post I started playing around a bit. I discovered that the headset MUST be connected to reproduce the failure. If I turn off the headset, PCPanel software will launch. I can then turn the headset ON AFTER PCPanel is opened and everything works as expected. I am still not getting any log output to %localappdata%\CrashDumps so I can't provide anything else. 

Thanks for all your work on this project, it is hugely appreciated.

**Comment by nvdweem** [comment] 2022-11-09 07:01
Too bad that there aren't any crashdumps. I'm not sure if they are enabled by default or only when there is some debugging software installed. 
I'll try and see if it's possible to add a registry entry so othat the dumps are written anyway.

I created a new snapshot build yesterday which does some additional checks to prevent crashing. You could try that one to see if it just happens to fix your issue too.

**Comment by nvdweem** [comment] 2022-11-17 19:45
@iamnotracist, have you tried the latest build yet? Does it prevent the crashing?

**Comment by iamnotracist** [comment] 2022-11-19 22:08
Just installed it this afternoon. So far, no crashes. It starts up & seems to be working! Thank you!

**Comment by nvdweem** [comment] 2022-11-26 15:08
Closing the issue as it seems to be fixed.

**Closed by nvdweem** 2022-11-26 15:08 UTC
Labels: bug
